run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gosec
    - bodyclose
    - noctx
    - prealloc

  disable:
    - depguard
    - exhaustive

linters-settings:
  errcheck:
    check-blank: false
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  gosec:
    excludes:
      - G101
      - G104
      - G304

  misspell:
    locale: US

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/PipeOpsHQ/agent-sdk-go

issues:
  exclude-dirs:
    - vendor
    - .git
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - unparam
        - errcheck

    - linters:
        - staticcheck
      text: "SA1019:"

    - linters:
        - unparam
      text: "is always"

  max-issues-per-linter: 50
  max-same-issues: 10
